### PR TITLE
Fix release npm package job

### PR DESCRIPTION
**Pull request by sosukesuzuki**
- Refer to the `@cybozu/protobuf` in workspaces
- Set up Git user in GitHub Actions
- Commit and push after running `npm version` and `npm publish`

### CODE REVIEW

**Comment by ymmt2005** [comment]
> Commit and push after running npm version and npm publish

Why do you want to create and push a commit?

**Comment by sosukesuzuki** [comment]
@ymmt2005 `npm version` updates `version` field of `./es/package.json`. So we need to manually commit & push the changes to git.

**Comment by ymmt2005** [comment]
@sosukesuzuki 
I don't see any `version` field in that file...
https://github.com/cybozu/protobuf/blob/main/es/package.json

Maybe it is added with `npm version`?
In that case, I guess we can ignore the diff made by `npm version`.

**Comment by sosukesuzuki** [comment]
Sorry, I was wrong. The correct path is `./es/packages/**/package.json`
https://github.com/cybozu/protobuf/blob/main/es/packages/protobuf/package.json#L3 and https://github.com/cybozu/protobuf/blob/main/es/packages/protoc-gen-es-cybozu-validate/package.json#L2

**Comment by ymmt2005** [comment]
I see. Thanks.

**Pull request merged**
